image: mcr.microsoft.com/azure-cli

stages:
  - validate
  - plan
  - apply

variables:
  TF_DEV_ROOT: "terraform/environments/azure/dev"
  TF_PROD_ROOT: "terraform/environments/azure/prod"

before_script:
  # Dynamic environment selection
  - |
    if [[ "$CI_COMMIT_REF_NAME" == "prod" ]]; then
      export TF_ROOT=$TF_PROD_ROOT
      export ARM_SUBSCRIPTION_ID=$PROD_ARM_SUBSCRIPTION_ID
    else
      export TF_ROOT=$TF_DEV_ROOT
      export ARM_SUBSCRIPTION_ID=$DEV_ARM_SUBSCRIPTION_ID
    fi
  - cd $TF_ROOT

  # Azure OIDC login correctly
  - echo "Authenticating to Azure with OIDC"
  - az login --service-principal --username $ARM_CLIENT_ID --federated-token $CI_JOB_JWT_V2 --tenant $ARM_TENANT_ID
  - az account set --subscription $ARM_SUBSCRIPTION_ID
  - terraform init -input=false


validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - dev
    - prod
