image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

stages:
  - validate
  - plan
  - apply
  - cleanup

variables:
  TF_ROOT: terraform
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_PLUGIN_CACHE_DIR: "$CI_PROJECT_DIR/.terraform.d/plugin-cache"

.terraform-cache: &terraform-cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ${TF_ROOT}/.terraform
      - .terraform.d/plugin-cache
    policy: pull-push

.before_script_common: &before_script_common
  - echo "Starting job in $CI_JOB_STAGE stage"
  - cd ${TF_ROOT}
  - export TF_VAR_client_id=$ARM_CLIENT_ID
  - export TF_VAR_client_secret=$ARM_CLIENT_SECRET
  - export TF_VAR_tenant_id=$ARM_TENANT_ID
  - export TF_VAR_subscription_id=$ARM_SUBSCRIPTION_ID

validate:
  stage: validate
  <<: *terraform-cache
  before_script:
    - *before_script_common
  script:
    - terraform init -backend=false
    - terraform validate
    - terraform fmt -check -diff
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod"'

plan:
  stage: plan
  <<: *terraform-cache
  before_script:
    - *before_script_common
  script:
    - terraform init
    - terraform plan --var-file=tfvars_files/dev.tfvars -out=tfplan
    - terraform show -json tfplan > plan.json
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
      - ${TF_ROOT}/plan.json
    reports:
      terraform: ${TF_ROOT}/plan.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod"'

apply:
  stage: apply
  <<: *terraform-cache
  before_script:
    - *before_script_common
  script:
    - terraform init
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod"'
      when: manual
      allow_failure: false
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
      allow_failure: true
  environment:
    name: $CI_COMMIT_BRANCH
    deployment_tier: development

cleanup:
  stage: cleanup
  <<: *terraform-cache
  before_script:
    - *before_script_common
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: manual
      allow_failure: true
  environment:
    name: $CI_COMMIT_BRANCH
    action: stop
