apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-app-of-apps
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://gitlab.com/microservices1691715/deployment.git
    targetRevision: main
    path: "applications/dev/"
  destination:
    server: "https://kubernetes.default.svc"