---
#--------------------------------------------------------------
# Values for the Argo CD Helm chart
# For further configuration parameters please check terraform-config/argocd.tf
#--------------------------------------------------------------

## Argo Configs
configs:
  # General Argo CD configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    # -- Enable Status Badge
    ## Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/status-badge/
    statusbadge.enabled: true
    exec.enabled: true
    ui.bannerpermanent: true

  # Create the argocd-initial-admin-secret
  createSecret: true

  # Argo CD configuration parameters
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  params:
    server.insecure: true
    server.basehref: /argocd
    server.rootpath: /argocd

## Server
server:
  # TLS certificate configuration via cert-manager
  ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
  certificate:
    # -- Deploy a Certificate resource (requires cert-manager)
    enabled: true
    # Certificate issuer
    ## Ref: https://cert-manager.io/docs/concepts/issuer
    issuer:
      # -- Certificate issuer group. Set if using an external issuer. Eg. `cert-manager.io`
      group: "cert-manager.io"
      # -- Certificate issuer kind. Either `Issuer` or `ClusterIssuer`
      kind: "ClusterIssuer"
      # -- Certificate issuer name. Eg. `letsencrypt`
      name: "letsencrypt-production-cluster-issuer"
  # TLS certificate configuration via Secret
  ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
  certificateSecret:
    # -- Create argocd-server-tls secret
    enabled: true
  # Argo CD server ingress configuration
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: false
    # -- Defines which ingress controller will implement the resource
    ingressClassName: "nginx"
    # -- The path to Argo CD server
    path: /argocd
    # -- Enable TLS configuration for the hostname defined at `server.ingress.hostname`
    ## TLS certificate will be retrieved from a TLS secret `argocd-server-tls`
    ## You can create this secret via `certificate` or `certificateSecret` option
    tls: true

  metrics:
    enabled: true
    service:
      # Optional: customize service settings
      annotations: {}
    serviceMonitor:
      enabled: true

controller:
  metrics:
    enabled: true
    service:
      annotations: {}
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    service:
      annotations: {}
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    service:
      annotations: {}
    serviceMonitor:
      enabled: true
