apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev
                  registry: acrmicroservices1691717dev.azurecr.io
                  provider: azure
          - list:
              elements:
                - name: catalog
                  path: catalog
                - name: audit
                  path: audit
                - name: orders
                  path: orders
                - name: micro-market-frontend
                  path: micro-market-frontend
  template:
    metadata:
      name: '{{name}}-{{env}}'
      namespace: argocd
      labels:
        environment: '{{env}}'
        provider: '{{provider}}'
    spec:
      project: microservices
      source:
        repoURL: https://gitlab.com/microservices1691715/deployment.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - environments/{{env}}-values.yaml
          parameters:
            - name: global.environment
              value: '{{env}}'
            - name: image.repository
              value: '{{registry}}/microservices1691717/{{name}}'
            - name: global.domain
              value: 'microservices1691717.westeurope.cloudapp.azure.com'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'microservices'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
