global:
  image:
    repository: quay.io/argoproj/argocd
    tag: v2.10.2

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  externalConfig: false
  existingSecret: false
  createSecret: true

configs:
  cm:
    admin.enabled: true
    timeout.reconciliation: 180s
    application.instanceLabelKey: argocd.argoproj.io/instance
    url: "${ARGOCD_URL}"
    oidc.config: |
      name: Keycloak
      issuer: "${KEYCLOAK_ISSUER}"
      clientID: argocd
      clientSecret: $argo-oidc-client-secret
      requestedScopes: ["openid", "profile", "email", "groups"]

  params:
    server.insecure: false
    server.basehref: /argocd
    server.rootpath: /argocd
    server.staticassets: /argocd

  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, *, *, allow
      p, role:org-admin, projects, *, *, allow
      g, admin, role:org-admin

server:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  certificate:
    enabled: true
    issuer:
      group: "cert-manager.io"
      kind: "ClusterIssuer"
      name: "letsencrypt-staging-cluster-issuer"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /argocd
    pathType: Prefix
    https: true
    tls:
      - hosts:
          - "${DOMAIN}"
        secretName: argocd-server-tls
    hosts:
      - "${DOMAIN}"
    extraPaths:
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      nginx.ingress.kubernetes.io/service-upstream: "true"
      nginx.ingress.kubernetes.io/upstream-vhost: "${DOMAIN}"
      nginx.ingress.kubernetes.io/proxy-set-headers: "true"
      nginx.ingress.kubernetes.io/proxy-set-header-X-Forwarded-Proto: "$scheme"
      nginx.ingress.kubernetes.io/proxy-set-header-X-Forwarded-Host: "$host"
      nginx.ingress.kubernetes.io/proxy-set-header-X-Forwarded-Uri: "$request_uri"
      nginx.ingress.kubernetes.io/proxy-set-header-X-Forwarded-For: "$proxy_add_x_forwarded_for"
      nginx.ingress.kubernetes.io/proxy-set-header-X-Real-IP: "$remote_addr"

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

applicationSet:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
