apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: "Project for infrastructure applications"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      name: "*"
      server: https://kubernetes.default.svc