prometheus:
  prometheusSpec:
    retention: "30d"
    evaluationInterval: "60s"
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: ""
    serviceMonitorNamespaceSelector: ""
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: ""
    podMonitorNamespaceSelector: ""
    scrapeConfigSelectorNilUsesHelmValues: false
    scrapeConfigSelector: ""
    scrapeConfigNamespaceSelector: ""
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "managed-csi"
          resources:
            limits:
              memory: 3000Mi

grafana:
  assertNoLeakedSecrets: false
  adminPassword: "${random_password.grafana_password.result}"
  grafana.ini:
    server:
      domain: "${local.current_domain}"
      root_url: "https://${local.current_domain}/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: false
  serviceMonitor:
    enabled: true
    scrapeTimeout: "30s"
  additionalDataSources:
    - name: "loki"
      type: "loki"
      default: true
      access: "proxy"
      url: "http://loki-gateway.monitoring.svc.cluster.local"
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "test"
      editable: true

defaultRules:
  rules:
    kubeScheduler: false
  disabled:
    KubeControllerManagerDown: true
    KubeSchedulerDown: true

kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      component: kube-proxy

kubeControllerManager:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false

kubeScheduler:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false
