apiVersion: tf.argoproj.io/v1alpha1
kind: Terraform
metadata:
  name: dev-infra
spec:
  path: .
  sourceRef:
    repoURL: 'https://gitlab.com/microservices1691715/infrastructure.git'
    targetRevision: dev
    path: terraform/environments/dev
  approvePlanAuto: true
  backend:
    s3:
      bucket: "terraform-state-bucket"
      key: "dev/terraform.tfstate"
      region: "us-east-1"
      credentialsSecretRef:
        name: aws-creds
        key: credentials
  runner:
    image: hashicorp/terraform:1.6.0
