server:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
